kind: Service
apiVersion: v1
metadata:
  name: perftest
  namespace: perftest
spec:
  type: LoadBalancer
  selector:
    app: sample
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web